//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.13 at 10:52:57 AM JST 
//


package com.poc.example.ws.jaxb.wsinput;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.poc.example.ws.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.poc.example.ws.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Wsinput }
     * 
     */
    public Wsinput createWsinput() {
        return new Wsinput();
    }

    /**
     * Create an instance of {@link Wsinput.Inputs }
     * 
     */
    public Wsinput.Inputs createWsinputInputs() {
        return new Wsinput.Inputs();
    }

}
