//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.13 at 10:52:57 AM JST 
//


package com.poc.example.ws.jaxb.wsinput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inputs">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="argumentA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="argumentB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputs"
})
@XmlRootElement(name = "wsinput")
public class Wsinput {

    @XmlElement(required = true)
    protected Wsinput.Inputs inputs;

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link Wsinput.Inputs }
     *     
     */
    public Wsinput.Inputs getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wsinput.Inputs }
     *     
     */
    public void setInputs(Wsinput.Inputs value) {
        this.inputs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="argumentA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="argumentB" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "argumentA",
        "argumentB"
    })
    public static class Inputs {

        @XmlElement(required = true)
        protected String argumentA;
        @XmlElement(required = true)
        protected String argumentB;

        /**
         * Gets the value of the argumentA property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArgumentA() {
            return argumentA;
        }

        /**
         * Sets the value of the argumentA property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArgumentA(String value) {
            this.argumentA = value;
        }

        /**
         * Gets the value of the argumentB property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArgumentB() {
            return argumentB;
        }

        /**
         * Sets the value of the argumentB property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArgumentB(String value) {
            this.argumentB = value;
        }

    }

}
